---
name: ajep-os
description: This is my personal OS image.
base-image: registry.fedoraproject.org/fedora-kinoite
image-version: 41 # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - installrpmfusion.sh

  - type: rpm-ostree
    install:
      - neovim
      - chromium
      - htop
      - python3-neovim
      - zsh
      - tmux
      - kvantum
      - hyprland
      - keepassxc
      - copyq
      - distrobox
      - libva-utils
      - rclone
      - NetworkManager-ovs
      - pavucontrol-qt
      - cockpit
      - cockpit-files
      - cockpit-machines
      - cockpit-networkmanager
      - cockpit-ostree
      - cockpit-podman
      - cockpit-selinux
      - cockpit-storaged
      - qt5ct
      - qt6ct
      - papirus-icon-theme
      - papirus-icon-theme-dark
      - autojump
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - sysstat
      - python3-pip
      - waybar
      - wofi
      - kate
      - intel-media-driver
      - snapper
      - btrbk
      - libvirt-daemon-kvm
      - syncthing
    remove:
      - toolbox

  - type: script
    scripts:
      - rpmostreeoverride.sh

  - type: default-flatpaks
    notify: true 
    system:
      repo-name: flathub
      repo-title: "Flathub (system-wide)" 
      install:
        - tv.kodi.Kodi
        - io.mpv.Mpv
        - io.freetubeapp.FreeTube
        - com.rustdesk.RustDesk
        - com.anydesk.Anydesk
        - com.vscodium.codium
        - org.libreoffice.LibreOffice
        - org.kde.kamoso
        - org.kde.kolourpaint
        - org.virt_manager.virt-manager

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

